import { Link } from "react-router-dom";
import { useAsync } from "../hooks/useAsync";
import { useRecentQueries } from "../hooks/useRecentQueries";
import { filmApi } from "../api/client";
import { DATA_SOURCE } from "../lib/constants";
import { PageHeader } from "../components/layout/PageHeader";
import { StatCard } from "../components/dashboard/StatCard";
import { RecentQueries } from "../components/dashboard/RecentQueries";
import { Button } from "../components/ui/Button";
import { LoadingSpinner } from "../components/ui/LoadingSpinner";
import { ErrorBanner } from "../components/ui/ErrorBanner";
import { Card } from "../components/ui/Card";

export function DashboardPage() {
  const { queries } = useRecentQueries();
  const stats = useAsync(() => filmApi.getStats(), [], "stats");

  return (
    <div>
      <PageHeader
        title="Dashboard"
        description="Consult developing times and generate recipes from normalized DigitalTruth gold data."
        action={
          <Link to="/search">
            <Button>New query</Button>
          </Link>
        }
      />

      {stats.loading ? <LoadingSpinner label="Loading dataset stats…" /> : null}
      {stats.error ? (
        <ErrorBanner
          message={stats.error.message}
          hint={stats.error.hint}
          onRetry={stats.reload}
        />
      ) : null}

      {stats.data ? (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <StatCard label="Films" value={stats.data.films} hint="Gold dimension" />
          <StatCard label="Developers" value={stats.data.developers} hint="Gold dimension" />
          <StatCard
            label="Film + developer combinations"
            value={stats.data.developing_time_combinations}
            hint="Developing time fact rows"
          />
        </div>
      ) : null}

      <div className="mt-8 grid gap-6 lg:grid-cols-2">
        <RecentQueries queries={queries} />
        <Card title="About this project">
          <p className="text-sm leading-6 text-muted">
            Medallion pipeline: scrape → silver parquet → gold star schema. The web UI
            reads gold data only; recipe steps are generated by your configured LLM
            using lookup times as ground truth.
          </p>
          <dl className="mt-4 space-y-2 text-sm">
            <div className="flex justify-between gap-4">
              <dt className="text-muted">Source</dt>
              <dd className="font-medium text-ink">{DATA_SOURCE}</dd>
            </div>
            {stats.data?.source_hash ? (
              <div className="flex justify-between gap-4">
                <dt className="text-muted">Dataset hash</dt>
                <dd className="font-mono text-xs text-ink">{stats.data.source_hash}</dd>
              </div>
            ) : null}
          </dl>
        </Card>
      </div>
    </div>
  );
}
